# Generated by Django 6.0.6 on 2026-06-19 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Grievance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='grievances/images/')),
                ('location_manual_note', models.TextField(blank=True)),
                ('ml_translated_text', models.TextField(blank=True)),
                ('ml_summary', models.TextField(blank=True)),
                ('ml_department_suggestion', models.CharField(blank=True, max_length=50)),
                ('ml_priority_suggestion', models.CharField(blank=True, max_length=20)),
                ('ml_is_spam', models.BooleanField(blank=True, null=True)),
                ('ml_is_duplicate', models.BooleanField(blank=True, null=True)),
                ('ml_duplicate_type', models.CharField(blank=True, max_length=10)),
                ('ml_image_valid', models.BooleanField(blank=True, null=True)),
                ('ml_location_extracted', models.TextField(blank=True)),
                ('ml_processed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('RECEIVED', 'Received'), ('PROCESSING', 'Processing'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected'), ('REOPENED', 'Reopened'), ('CLOSED', 'Closed')], default='SUBMITTED', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('resolution_note', models.TextField(blank=True)),
                ('reopen_count', models.PositiveIntegerField(default=0)),
                ('last_reopened_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_grievances', to=settings.AUTH_USER_MODEL)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grievances', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grievances', to='departments.department')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_grievances', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
