# Generated by Django 6.0.6 on 2026-06-20 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0005_module8_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grievancetimelineevent',
            name='event_type',
            field=models.CharField(choices=[('SUBMITTED', 'Submitted'), ('ASSIGNED', 'Assigned'), ('REASSIGNED', 'Reassigned'), ('IN_PROGRESS', 'In Progress'), ('PENDING_FIELD_VISIT', 'Pending Field Visit'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened'), ('REJECTED', 'Rejected'), ('EVIDENCE_UPLOADED', 'Evidence Uploaded'), ('SLA_REMINDER', 'SLA Reminder'), ('SLA_BREACHED', 'SLA Breached'), ('SLA_ESCALATED', 'SLA Escalated')], max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('GRIEVANCE_SUBMITTED', 'Grievance Submitted'), ('OFFICER_ASSIGNED', 'Officer Assigned'), ('STATUS_CHANGED', 'Status Changed'), ('ESCALATED', 'Escalated'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened'), ('EVIDENCE_UPLOADED', 'Evidence Uploaded'), ('SLA_REMINDER', 'SLA Reminder'), ('SLA_BREACHED', 'SLA Breached'), ('SLA_ESCALATED', 'SLA Escalated')], max_length=30),
        ),
    ]
